// Source-of-truth for the hook script that the Claude CLI runs
// after every `Write` / `Edit` tool call (#763 PR 2 prereq).
//
// The string below is written to
// `<workspace>/.claude/hooks/wiki-snapshot.mjs` at server startup
// by `wiki-history-provisioning.ts`. We keep the script as a
// constant rather than a real source file so:
//
//   1. The mulmoclaude server only ships one binary; provisioning
//      can recreate the hook on any workspace without copy-from
//      paths varying between dev / prod / docker layouts.
//   2. Updating the hook is a single TypeScript constant change —
//      next server start re-provisions automatically (idempotent).
//
// Behaviour:
//   - Read stdin JSON (claude CLI feeds tool_input + tool_response).
//   - If the touched file is `data/wiki/pages/<slug>.md` under the
//     workspace root, POST `{ absPath, reason? }` to the parent
//     server's `/api/wiki/internal/snapshot` endpoint.
//   - Anything else: silent no-op. The hook MUST NOT fail loud;
//     a busted snapshot path can't be allowed to make `Write`
//     itself look like it failed to the LLM.

export const WIKI_SNAPSHOT_HOOK_SCRIPT = `#!/usr/bin/env node
// Auto-generated by mulmoclaude server (#763). Edits to this file
// will be overwritten on the next server start. Source of truth is
// server/workspace/wiki-history/hookScript.ts.

import { readFileSync } from "node:fs";
import { homedir } from "node:os";
import path from "node:path";

const WORKSPACE_ROOT = path.join(homedir(), "mulmoclaude");
const WIKI_PAGES_DIR = path.join(WORKSPACE_ROOT, "data", "wiki", "pages");
const TOKEN_PATH = path.join(WORKSPACE_ROOT, ".session-token");
const PORT_PATH = path.join(WORKSPACE_ROOT, ".server-port");

async function readStdin() {
  const chunks = [];
  for await (const chunk of process.stdin) chunks.push(chunk);
  const raw = Buffer.concat(chunks).toString("utf-8");
  if (!raw.trim()) return null;
  try {
    return JSON.parse(raw);
  } catch {
    return null;
  }
}

function extractFilePath(payload) {
  // Claude CLI hook payload: { tool_name, tool_input, tool_response, ... }
  // Different tools surface the path under different keys —
  // check both shapes defensively.
  const fromInput = payload?.tool_input?.file_path;
  if (typeof fromInput === "string") return fromInput;
  const fromResponse = payload?.tool_response?.filePath;
  if (typeof fromResponse === "string") return fromResponse;
  return null;
}

function isWikiPagePath(absPath) {
  if (!absPath.endsWith(".md")) return false;
  if (!absPath.startsWith(WIKI_PAGES_DIR + path.sep) && !absPath.startsWith(WIKI_PAGES_DIR + "/")) {
    return false;
  }
  // Reject nested paths — a real wiki page lives directly under
  // pages/, not in pages/<sub>/<file>.md. Mirrors the server-side
  // \`classifyAsWikiPage\` rule.
  const rel = absPath.slice(WIKI_PAGES_DIR.length + 1);
  if (rel.includes(path.sep)) return false;
  return true;
}

function readTokenSafe() {
  try {
    return readFileSync(TOKEN_PATH, "utf-8").trim();
  } catch {
    return "";
  }
}

function readPortSafe() {
  try {
    const raw = readFileSync(PORT_PATH, "utf-8").trim();
    const port = Number.parseInt(raw, 10);
    return Number.isInteger(port) && port > 0 && port < 65536 ? port : null;
  } catch {
    return null;
  }
}

async function main() {
  const payload = await readStdin();
  if (!payload) return;

  const filePath = extractFilePath(payload);
  if (!filePath || !isWikiPagePath(filePath)) return;

  const token = readTokenSafe();
  const port = readPortSafe();
  if (!token || !port) return; // server isn't reachable; silent no-op

  try {
    await fetch(\`http://127.0.0.1:\${port}/api/wiki/internal/snapshot\`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: \`Bearer \${token}\`,
      },
      body: JSON.stringify({ absPath: filePath }),
    });
  } catch {
    // Network / server down — drop silently. The wiki page write
    // itself already succeeded; missing one snapshot is recoverable
    // (the next save will record the next state).
  }
}

main().catch(() => {
  // Hooks run synchronously to the LLM tool flow — never throw.
});
`;
