// Pair each ToolResultComplete with the args of the tool call that
// produced it, so the sidebar source-label can render `name(action)`
// instead of bare `name`. The result envelope and the call history
// have no shared id (result.uuid is generated by the plugin REST
// handler; call.toolUseId comes from the agent), so we pair by
// arrival order: the i-th result of toolName X corresponds to the
// i-th call of toolName X. Tool calls execute serially in this
// codebase, so the ordering is stable in practice.
//
// KNOWN ISSUE — labels disappear after a hard refresh. `toolCallHistory`
// is an in-memory SSE byproduct, populated only while a run is live
// (see eventDispatch.ts on the `toolCall` branch). On reload, sessions
// are rehydrated from the on-disk chat log via parseSessionEntries,
// which only restores ToolResultComplete envelopes — the originating
// call args are NOT persisted, and buildLoadedSession resets
// `toolCallHistory: []` (sessionEntries.ts). Pairing therefore finds
// nothing to match and `sourceLabel` falls back to the bare toolName.
// Fixing this requires persisting args alongside the result (e.g. a
// `callArgs` field on the result envelope, written by plugin REST
// handlers and round-tripped through the chat log). Deferred until
// the label proves load-bearing enough to justify the schema change.

import type { ToolResultComplete } from "gui-chat-protocol/vue";
import type { ToolCallHistoryItem } from "../../types/toolCallHistory";

// Tool-call events from the agent carry the namespaced MCP form
// `mcp__<server>__<tool>` (e.g. `mcp__mulmoclaude__manageAccounting`),
// while result envelopes use the bare plugin name. Strip the prefix
// before matching so pairing works for MCP-routed plugins.
export function normalizeToolName(toolName: string): string {
  if (!toolName.startsWith("mcp__")) return toolName;
  const sep = toolName.indexOf("__", 5);
  return sep === -1 ? toolName : toolName.slice(sep + 2);
}

export function pairResultsWithCallArgs(results: readonly ToolResultComplete[], history: readonly ToolCallHistoryItem[]): Map<string, unknown> {
  const cursors = new Map<string, number>();
  const out = new Map<string, unknown>();
  for (const result of results) {
    const key = normalizeToolName(result.toolName);
    const next = cursors.get(key) ?? 0;
    let found = -1;
    for (let i = next; i < history.length; i++) {
      if (normalizeToolName(history[i].toolName) === key) {
        found = i;
        break;
      }
    }
    if (found === -1) continue;
    out.set(result.uuid, history[found].args);
    cursors.set(key, found + 1);
  }
  return out;
}

// Pick the user-facing detail string for a tool call's args. Prefer
// `action` (the convention across multi-feature plugins like
// manageAccounting / manageSkills / manageWiki); otherwise fall
// back to the first string-valued arg. Returns null when args have
// no useful scalar to show — caller should drop the parens.
export function pickCallArgLabel(args: unknown): string | null {
  if (!args || typeof args !== "object") return null;
  const record = args as Record<string, unknown>;
  if (typeof record.action === "string" && record.action) return record.action;
  for (const value of Object.values(record)) {
    if (typeof value === "string" && value) return value;
  }
  return null;
}
