// Unit tests for the LLM-write hook provisioning (#763 PR 2).
// Provisioning must be idempotent and must NOT clobber user-set
// keys in `.claude/settings.json` — the workspace's settings.json
// is a shared resource and we own only the single PostToolUse
// entry tagged `mulmoclaudeWikiHistory: true`.

import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, readFile, rm, writeFile, mkdir } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { provisionWikiHistoryHook } from "../../../server/workspace/wiki-history/provision.js";

interface SettingsShape {
  hooks?: { PostToolUse?: Array<Record<string, unknown>> };
  [key: string]: unknown;
}

async function readSettings(workspace: string): Promise<SettingsShape> {
  const raw = await readFile(path.join(workspace, ".claude", "settings.json"), "utf-8");
  return JSON.parse(raw) as SettingsShape;
}

describe("provisionWikiHistoryHook — first install", () => {
  it("creates settings.json + hook script with our PostToolUse entry", async () => {
    const root = await mkdtemp(path.join(tmpdir(), "wiki-prov-fresh-"));
    await provisionWikiHistoryHook({ workspaceRoot: root });

    const settings = await readSettings(root);
    const entries = settings.hooks?.PostToolUse ?? [];
    assert.equal(entries.length, 1);
    const entry = entries[0] as { matcher?: string; hooks?: Array<{ command?: string; mulmoclaudeWikiHistory?: boolean }> };
    assert.equal(entry.matcher, "Write|Edit");
    assert.equal(entry.hooks?.length, 1);
    const hook = entry.hooks?.[0];
    assert.equal(hook?.mulmoclaudeWikiHistory, true);
    assert.match(hook?.command ?? "", /node .+wiki-snapshot\.mjs/);

    const scriptPath = path.join(root, ".claude", "hooks", "wiki-snapshot.mjs");
    const scriptBody = await readFile(scriptPath, "utf-8");
    assert.match(scriptBody, /Auto-generated by mulmoclaude server/);
    assert.match(scriptBody, /\/api\/wiki\/internal\/snapshot/);

    await rm(root, { recursive: true, force: true });
  });
});

describe("provisionWikiHistoryHook — idempotent", () => {
  it("running twice produces byte-identical settings + script", async () => {
    const root = await mkdtemp(path.join(tmpdir(), "wiki-prov-idem-"));
    await provisionWikiHistoryHook({ workspaceRoot: root });
    const firstSettings = await readFile(path.join(root, ".claude", "settings.json"), "utf-8");
    const firstScript = await readFile(path.join(root, ".claude", "hooks", "wiki-snapshot.mjs"), "utf-8");

    await provisionWikiHistoryHook({ workspaceRoot: root });
    const secondSettings = await readFile(path.join(root, ".claude", "settings.json"), "utf-8");
    const secondScript = await readFile(path.join(root, ".claude", "hooks", "wiki-snapshot.mjs"), "utf-8");

    assert.equal(secondSettings, firstSettings, "settings.json should be unchanged on second provision");
    assert.equal(secondScript, firstScript, "hook script should be unchanged on second provision");

    await rm(root, { recursive: true, force: true });
  });
});

describe("provisionWikiHistoryHook — preserves user-set keys", () => {
  it("does not touch unrelated PostToolUse entries", async () => {
    const root = await mkdtemp(path.join(tmpdir(), "wiki-prov-merge-"));
    await mkdir(path.join(root, ".claude"), { recursive: true });
    const userOwned = {
      hooks: {
        PostToolUse: [{ matcher: "Bash", hooks: [{ type: "command", command: "echo 'user hook ran' >> /tmp/user-bash.log" }] }],
      },
      otherTopLevel: { foo: "bar" },
    };
    await writeFile(path.join(root, ".claude", "settings.json"), JSON.stringify(userOwned, null, 2), "utf-8");

    await provisionWikiHistoryHook({ workspaceRoot: root });
    const settings = await readSettings(root);

    // Top-level keys unrelated to hooks are preserved.
    assert.deepEqual(settings.otherTopLevel, { foo: "bar" });

    // The user's Bash hook is still present.
    const entries = settings.hooks?.PostToolUse ?? [];
    assert.equal(entries.length, 2);
    const bashEntry = entries.find((entry) => entry.matcher === "Bash");
    assert.ok(bashEntry, "user's Bash hook should survive");

    // Our Write|Edit hook is appended.
    const ours = entries.find((entry) => entry.matcher === "Write|Edit");
    assert.ok(ours, "our Write|Edit hook should be added");

    await rm(root, { recursive: true, force: true });
  });

  it("replaces an existing owned entry rather than duplicating it", async () => {
    // Simulate a stale install with the marker but a different
    // command — provisioning should overwrite rather than append.
    const root = await mkdtemp(path.join(tmpdir(), "wiki-prov-replace-"));
    await mkdir(path.join(root, ".claude"), { recursive: true });
    const stale = {
      hooks: {
        PostToolUse: [
          {
            matcher: "Write|Edit",
            hooks: [
              {
                type: "command",
                command: "node /old/path/wiki-snapshot.mjs",
                mulmoclaudeWikiHistory: true,
              },
            ],
          },
        ],
      },
    };
    await writeFile(path.join(root, ".claude", "settings.json"), JSON.stringify(stale, null, 2), "utf-8");

    await provisionWikiHistoryHook({ workspaceRoot: root });
    const fresh = await readSettings(root);
    const entries = fresh.hooks?.PostToolUse ?? [];
    assert.equal(entries.length, 1, "stale entry should be replaced, not duplicated");
    const ours = entries[0] as { hooks?: Array<{ command?: string }> };
    const newCommand = ours.hooks?.[0]?.command ?? "";
    const escapedRoot = root.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    const expectedPattern = new RegExp(`${escapedRoot}.*wiki-snapshot\\.mjs`);
    assert.match(newCommand, expectedPattern, "command should point at the current workspace path");

    await rm(root, { recursive: true, force: true });
  });
});
