// Codegen for `server/agent/plugin-names.ts`.
//
// Reads `config/plugins.registry.ts` (the manifest) and writes a
// fully-derived TypeScript file. Run via `yarn generate:plugins`
// (also runs from CI to assert the committed file is up to date).
//
// The generated file is NOT edited by hand — it's overwritten on
// every run. Manifest changes flow:
//
//   1. Edit `config/plugins.registry.ts`
//   2. `yarn generate:plugins`
//   3. Commit both
//
// CI: `yarn generate:plugins && git diff --exit-code -- server/agent/plugin-names.ts`
// trips when the manifest moves but the generated file isn't
// committed. Same pattern as `yarn build:hooks` for the wiki
// snapshot bundle.
//
// Phase 1a of #1043 covers `plugin-names.ts` only. `tools/index.ts`
// and `toolNames.ts` follow in Phase 1b — those have view-only /
// legacy / built-in entries that need extra manifest fields.

import path from "node:path";
import { fileURLToPath } from "node:url";
import { writeFileSync } from "node:fs";
import { PLUGIN_REGISTRY, type PluginRegistration } from "../config/plugins.registry.ts";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, "..");

const OUT_PATH = path.join(repoRoot, "server/agent/plugin-names.ts");

/** Capitalise first letter; the rest of the id is preserved (so
 *  `present3D` round-trips to `Present3DDef`). The result must be
 *  a valid TS identifier — manifest ids are tool name strings, all
 *  of which currently match `[a-zA-Z][a-zA-Z0-9]*`, so no further
 *  sanitisation needed. */
function defVarName(id: string): string {
  return `${id[0].toUpperCase()}${id.slice(1)}Def`;
}

/** Build the import line for one plugin row. Internal modules append
 *  `.js` (Node ESM resolves `.ts` → `.js` at compile time). External
 *  package specifiers stay as-is. */
function importLine(row: PluginRegistration): string {
  const isPackage = !row.importFrom.startsWith(".");
  const specifier = isPackage ? row.importFrom : `${row.importFrom}.js`;
  const varName = defVarName(row.id);
  if (row.importStyle === "default") {
    return `import ${varName} from "${specifier}";`;
  }
  return `import { TOOL_DEFINITION as ${varName} } from "${specifier}";`;
}

/** Render a dotted endpoint key as the matching bracket access:
 *  `"todos.dispatch"` → `API_ROUTES.todos.dispatch`. Generated code
 *  references the constant rather than embedding the URL literal so
 *  rename refactors on `apiRoutes.ts` propagate via TS errors. */
function endpointAccess(key: string): string {
  return `API_ROUTES.${key}`;
}

function generate(): string {
  const imports = PLUGIN_REGISTRY.map(importLine).join("\n");
  const endpoints = PLUGIN_REGISTRY.map((row) => `  [${defVarName(row.id)}.name]: ${endpointAccess(row.endpointKey)},`).join("\n");
  const defs = PLUGIN_REGISTRY.map((row) => `  ${defVarName(row.id)},`).join("\n");

  return `// AUTO-GENERATED by \`yarn generate:plugins\` from \`config/plugins.registry.ts\`.
// DO NOT EDIT BY HAND — your changes will be overwritten on the next
// codegen run. To add or modify a plugin: update the manifest and
// re-run \`yarn generate:plugins\`.
//
// CI runs the same codegen and asserts \`git diff --exit-code\` so a
// manifest edit without a regenerated file fails the build.

/**
 * Single source of truth for GUI plugin → API endpoint mapping.
 * Used by both agent.ts (to know which plugins are MCP-backed)
 * and mcp-server.ts (to route tool calls to endpoints).
 */

${imports}
import { API_ROUTES } from "../../src/config/apiRoutes.js";

/** Maps plugin tool name → REST API endpoint. */
export const TOOL_ENDPOINTS: Record<string, string> = {
${endpoints}
};

/** All ToolDefinition objects for package and local plugins. */
export const PLUGIN_DEFS = [
${defs}
];

/** Set of plugin names that have MCP tool definitions. */
export const MCP_PLUGIN_NAMES = new Set(Object.keys(TOOL_ENDPOINTS));
`;
}

function main(): void {
  const out = generate();
  writeFileSync(OUT_PATH, out, "utf-8");
  console.log(`[generate:plugins] wrote ${PLUGIN_REGISTRY.length} entries → ${path.relative(repoRoot, OUT_PATH)}`);
}

main();
