// AUTO-GENERATED by `yarn generate:plugins` from `config/plugins.registry.ts`.
// DO NOT EDIT BY HAND — your changes will be overwritten on the next
// codegen run. To add or modify a plugin: update the manifest and
// re-run `yarn generate:plugins`.
//
// CI runs the same codegen and asserts `git diff --exit-code` so a
// manifest edit without a regenerated file fails the build.

/**
 * Single source of truth for GUI plugin → API endpoint mapping.
 * Used by both agent.ts (to know which plugins are MCP-backed)
 * and mcp-server.ts (to route tool calls to endpoints).
 */

import ManageTodoListDef from "../../src/plugins/todo/definition.js";
import ManageAccountingDef from "../../src/plugins/accounting/definition.js";
import ManageCalendarDef from "../../src/plugins/scheduler/calendarDefinition.js";
import ManageAutomationsDef from "../../src/plugins/scheduler/automationsDefinition.js";
import PresentMulmoScriptDef from "../../src/plugins/presentMulmoScript/definition.js";
import ManageSkillsDef from "../../src/plugins/manageSkills/definition.js";
import ManageSourceDef from "../../src/plugins/manageSource/definition.js";
import PresentHtmlDef from "../../src/plugins/presentHtml/definition.js";
import PresentChartDef from "../../src/plugins/chart/definition.js";
import PresentDocumentDef from "../../src/plugins/markdown/definition.js";
import PresentSpreadsheetDef from "../../src/plugins/spreadsheet/definition.js";
import GenerateImageDef from "../../src/plugins/generateImage/definition.js";
import OpenCanvasDef from "../../src/plugins/canvas/definition.js";
import EditImagesDef from "../../src/plugins/editImages/definition.js";
import { TOOL_DEFINITION as PresentFormDef } from "../../src/plugins/presentForm/definition.js";
import { TOOL_DEFINITION as CreateMindMapDef } from "@gui-chat-plugin/mindmap";
import { TOOL_DEFINITION as PutQuestionsDef } from "@mulmochat-plugin/quiz";
import { TOOL_DEFINITION as Present3DDef } from "@gui-chat-plugin/present3d";
import { API_ROUTES } from "../../src/config/apiRoutes.js";

/** Maps plugin tool name → REST API endpoint. */
export const TOOL_ENDPOINTS: Record<string, string> = {
  [ManageTodoListDef.name]: API_ROUTES.todos.dispatch,
  [ManageAccountingDef.name]: API_ROUTES.accounting.dispatch,
  [ManageCalendarDef.name]: API_ROUTES.scheduler.base,
  [ManageAutomationsDef.name]: API_ROUTES.scheduler.base,
  [PresentMulmoScriptDef.name]: API_ROUTES.mulmoScript.save,
  [ManageSkillsDef.name]: API_ROUTES.skills.create,
  [ManageSourceDef.name]: API_ROUTES.sources.manage,
  [PresentHtmlDef.name]: API_ROUTES.html.present,
  [PresentChartDef.name]: API_ROUTES.chart.present,
  [PresentDocumentDef.name]: API_ROUTES.plugins.presentDocument,
  [PresentSpreadsheetDef.name]: API_ROUTES.plugins.presentSpreadsheet,
  [GenerateImageDef.name]: API_ROUTES.image.generate,
  [OpenCanvasDef.name]: API_ROUTES.plugins.canvas,
  [EditImagesDef.name]: API_ROUTES.image.edit,
  [PresentFormDef.name]: API_ROUTES.plugins.form,
  [CreateMindMapDef.name]: API_ROUTES.plugins.mindmap,
  [PutQuestionsDef.name]: API_ROUTES.plugins.quiz,
  [Present3DDef.name]: API_ROUTES.plugins.present3d,
};

/** All ToolDefinition objects for package and local plugins. */
export const PLUGIN_DEFS = [
  ManageTodoListDef,
  ManageAccountingDef,
  ManageCalendarDef,
  ManageAutomationsDef,
  PresentMulmoScriptDef,
  ManageSkillsDef,
  ManageSourceDef,
  PresentHtmlDef,
  PresentChartDef,
  PresentDocumentDef,
  PresentSpreadsheetDef,
  GenerateImageDef,
  OpenCanvasDef,
  EditImagesDef,
  PresentFormDef,
  CreateMindMapDef,
  PutQuestionsDef,
  Present3DDef,
];

/** Set of plugin names that have MCP tool definitions. */
export const MCP_PLUGIN_NAMES = new Set(Object.keys(TOOL_ENDPOINTS));
